In [1]:
pip install google-play-scraper

Collecting google-play-scraper
  Downloading google_play_scraper-1.2.7-py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 2.2 MB/s eta 0:00:00
Downloading google_play_scraper-1.2.7-py3-none-any.whl (28 kB)
Installing collected packages: google-play-scraper
Successfully installed google-play-scraper-1.2.7

In [2]:
from google_play_scraper import reviews, Sort
import pandas as pd

In [11]:
all_reviews = []
continuation_token = None

# Fetch in batches
for _ in range(5):  # 5 batches x 200 = 1000 reviews
    result, continuation_token = reviews(
        'com.einnovation.temu',
        lang='en',
        country='us',
        sort=Sort.NEWEST,
        count=200,
        continuation_token=continuation_token
    )
    all_reviews.extend(result)
    if not continuation_token:
        break

# Convert to DataFrame
df = pd.DataFrame(all_reviews)[['userName', 'score', 'content', 'at', 'thumbsUpCount']]
df.to_csv('temu_reviews.csv', index=False)
print(f"Saved {len(df)} reviews")
print("Shape: " ,df.shape)

Saved 1000 reviews
Shape:  (1000, 5)

In [12]:
df.head()

,userName,score,content,at,thumbsUpCount
0,Arden Parmenter,5,so far it's great shopping,2026-03-08 19:33:09,0
1,suzanne tehako,5,"have been very happy with purchases. Thanks, T...",2026-03-08 19:33:06,0
2,Maikol Maikol,1,I can't see a menu you keep blowing with spin ...,2026-03-08 19:31:26,0
3,Asokere Edayomi,5,You are improving in your daily transactions. ...,2026-03-08 19:31:18,0
4,J C,2,I've found a few fantastic products the rest a...,2026-03-08 19:30:18,0

In [15]:
all_reviews = []
continuation_token = None

# Fetch in batches
for _ in range(5):  # 5 batches x 200 = 1000 reviews
    result, continuation_token = reviews(
        'com.amazon.mShop.android.shopping',
        lang='en',
        country='us',
        sort=Sort.NEWEST,
        count=200,
        continuation_token=continuation_token
    )
    all_reviews.extend(result)
    if not continuation_token:
        break

# Convert to DataFrame
df = pd.DataFrame(all_reviews)[['userName', 'score', 'content', 'at', 'thumbsUpCount']]
df.to_csv('amzon_reviews.csv', index=False)
print(f"Saved {len(df)} reviews")
print("Shape: " ,df.shape)

Saved 1000 reviews
Shape:  (1000, 5)

In [16]:
df.head()

,userName,score,content,at,thumbsUpCount
0,Tomislav,1,"very bad and laggy app, had big problems with ...",2026-03-08 19:33:25,0
1,Andrea Carter,5,"Love, Love Love these earrings ❤️",2026-03-08 19:25:24,0
2,Mackenzie Feeley,1,app if crashing ever since last update. cleare...,2026-03-08 19:20:08,0
3,Nunaya Bidnez,4,Just over the last couple weeks the Amazon app...,2026-03-08 19:18:32,0
4,Christopher Kovacs,1,Lies about shipping frequently to get you to p...,2026-03-08 19:15:28,0

In [17]:
all_reviews = []
continuation_token = None

# Fetch in batches
for _ in range(5):  # 5 batches x 200 = 1000 reviews
    result, continuation_token = reviews(
        'com.noon.buyerapp',
        lang='en',
        country='us',
        sort=Sort.NEWEST,
        count=200,
        continuation_token=continuation_token
    )
    all_reviews.extend(result)
    if not continuation_token:
        break

# Convert to DataFrame
df = pd.DataFrame(all_reviews)[['userName', 'score', 'content', 'at', 'thumbsUpCount']]
df.to_csv('noon_reviews.csv', index=False)
print(f"Saved {len(df)} reviews")
print("Shape: " ,df.shape)

Saved 1000 reviews
Shape:  (1000, 5)

In [18]:
df.head()

,userName,score,content,at,thumbsUpCount
0,Kwesi Appiah,5,Very reliable and fastest delivery,2026-03-08 19:37:38,0
1,MD:Nayem ISlAM,5,very good,2026-03-08 18:44:07,0
2,Mir Hossain,5,👍,2026-03-08 18:23:38,0
3,Thusanthan Thilak,5,it's my first order but I feel better thanks,2026-03-08 18:06:56,0
4,Haneen Dawoud,5,good,2026-03-08 17:39:25,0

In [19]:
all_reviews = []
continuation_token = None

# Fetch in batches
for _ in range(5):  # 5 batches x 200 = 1000 reviews
    result, continuation_token = reviews(
        'com.alibaba.aliexpresshd',
        lang='en',
        country='us',
        sort=Sort.NEWEST,
        count=200,
        continuation_token=continuation_token
    )
    all_reviews.extend(result)
    if not continuation_token:
        break

# Convert to DataFrame
df = pd.DataFrame(all_reviews)[['userName', 'score', 'content', 'at', 'thumbsUpCount']]
df.to_csv('ali-express_reviews.csv', index=False)
print(f"Saved {len(df)} reviews")
print("Shape: " ,df.shape)

Saved 1000 reviews
Shape:  (1000, 5)

In [20]:
df.head()

,userName,score,content,at,thumbsUpCount
0,sathish malamkunnu,1,What is this? What a price for the goods. temu...,2026-03-08 19:31:38,0
1,Patryk,1,"Na stronie z punktami, pokazują się losowe zni...",2026-03-08 17:43:07,0
2,Rick Hess,5,so far everything I have ordered has been fine...,2026-03-08 17:14:09,0
3,Bertha Mata,5,i love them i will continue to order from here...,2026-03-08 17:08:19,0
4,Lion Soldier,3,"Title: Great app, but impossible to pay in Gha...",2026-03-08 17:03:02,0