In [3]:
from google_play_scraper import reviews, Sort
import pandas as pd

In [4]:
all_reviews = []
continuation_token = None

# Fetch in batches
for _ in range(5):  # 5 batches x 200 = 1000 reviews
    result, continuation_token = reviews(
        'com.einnovation.temu',
        lang='en',
        country='us',
        sort=Sort.NEWEST,
        count=200,
        continuation_token=continuation_token
    )
    all_reviews.extend(result)
    if not continuation_token:
        break

# Convert to DataFrame
df = pd.DataFrame(all_reviews)[['userName', 'score', 'content', 'at', 'thumbsUpCount']]
df.to_csv('temu_reviews.csv', index=False)
print(f"Saved {len(df)} reviews")
print("Shape: " ,df.shape)

Saved 1000 reviews
Shape:  (1000, 5)

In [5]:
df.head()

,userName,score,content,at,thumbsUpCount
0,Phumza Myekelwa,5,good,2026-03-12 23:48:48,0
1,Troy M,5,love my stuff,2026-03-12 23:48:42,0
2,Shaun Minahan,5,Great service. It's only brain-dead couriers t...,2026-03-12 23:47:54,0
3,Lennox Robinson,4,My sisters and other relatives are ok with it ...,2026-03-12 23:45:43,0
4,Jessica Aughtman-McGrath,5,The stuff is always on time! I haven't had any...,2026-03-12 23:44:45,0

In [6]:
all_reviews = []
continuation_token = None

# Fetch in batches
for _ in range(5):  # 5 batches x 200 = 1000 reviews
    result, continuation_token = reviews(
        'com.amazon.mShop.android.shopping',
        lang='en',
        country='us',
        sort=Sort.NEWEST,
        count=200,
        continuation_token=continuation_token
    )
    all_reviews.extend(result)
    if not continuation_token:
        break

# Convert to DataFrame
df = pd.DataFrame(all_reviews)[['userName', 'score', 'content', 'at', 'thumbsUpCount']]
df.to_csv('amzon_reviews.csv', index=False)
print(f"Saved {len(df)} reviews")
print("Shape: " ,df.shape)

Saved 1000 reviews
Shape:  (1000, 5)

In [7]:
df.head()

,userName,score,content,at,thumbsUpCount
0,Franklin McInnis,5,Time Saving,2026-03-12 23:42:32,0
1,Helen Lord,5,hope this helps,2026-03-12 23:19:09,0
2,Menna Assem,1,برنامج سئ,2026-03-12 22:54:13,0
3,Clynt Barker,1,"Order placed, but no tracking available. Notif...",2026-03-12 22:47:10,0
4,Richie Tozier,2,lower your damn security I've made three diffe...,2026-03-12 22:28:21,0

In [8]:
all_reviews = []
continuation_token = None

# Fetch in batches
for _ in range(5):  # 5 batches x 200 = 1000 reviews
    result, continuation_token = reviews(
        'com.noon.buyerapp',
        lang='en',
        country='us',
        sort=Sort.NEWEST,
        count=200,
        continuation_token=continuation_token
    )
    all_reviews.extend(result)
    if not continuation_token:
        break

# Convert to DataFrame
df = pd.DataFrame(all_reviews)[['userName', 'score', 'content', 'at', 'thumbsUpCount']]
df.to_csv('noon_reviews.csv', index=False)
print(f"Saved {len(df)} reviews")
print("Shape: " ,df.shape)

Saved 1000 reviews
Shape:  (1000, 5)

In [9]:
df.head()

,userName,score,content,at,thumbsUpCount
0,Noman Tanoli,4,Fast Delivery nd product is also Good,2026-03-12 23:44:07,0
1,Aftab Baloch,5,good,2026-03-12 22:31:15,0
2,K Shroif,5,good sarbic,2026-03-12 22:28:33,0
3,Boda Mahmoud,5,easy to use,2026-03-12 22:21:35,0
4,Noorudeen Ahammedu kunju,2,Good,2026-03-12 21:57:05,0

In [10]:
all_reviews = []
continuation_token = None

# Fetch in batches
for _ in range(5):  # 5 batches x 200 = 1000 reviews
    result, continuation_token = reviews(
        'com.alibaba.aliexpresshd',
        lang='en',
        country='us',
        sort=Sort.NEWEST,
        count=200,
        continuation_token=continuation_token
    )
    all_reviews.extend(result)
    if not continuation_token:
        break

# Convert to DataFrame
df = pd.DataFrame(all_reviews)[['userName', 'score', 'content', 'at', 'thumbsUpCount']]
df.to_csv('ali-express_reviews.csv', index=False)
print(f"Saved {len(df)} reviews")
print("Shape: " ,df.shape)

Saved 1000 reviews
Shape:  (1000, 5)

In [11]:
df.head()

,userName,score,content,at,thumbsUpCount
0,Kayanat Anika,1,honestly I think there is a problem cuz I can'...,2026-03-12 23:21:40,0
1,Nunya Biz,5,Apparently when I set settings for notificatio...,2026-03-12 22:42:39,4
2,Samarth Sandeep,1,this is by far the worst app I have bought 3 p...,2026-03-12 22:14:26,0
3,Rubysu aka Natalie Debler,3,"My first package arrived, but with COUNTERFEIT...",2026-03-12 21:38:03,0
4,Toni Dawn Moore,4,never shopped there yet,2026-03-12 21:24:39,0